[program:basestom-bot]
command=/opt/basestom-bot/venv/bin/python /opt/basestom-bot/src/bot.py
directory=/opt/basestom-bot
user=your_username
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/basestom-bot.err.log
stdout_logfile=/var/log/basestom-bot.out.log
environment=PYTHONUNBUFFERED="1"
